# Generated by Django 4.0.4 on 2023-03-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hoduser_level_studentuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.hoduser'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(blank=True, max_length=2550, null=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Department Name'),
        ),
    ]
